basePath: /v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/meters/{id}:
    delete:
      consumes:
      - application/json
      description: Delete meters
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - type: object
            - properties:
                data:
                  allOf:
                  - type: object
                  - properties:
                      code:
                        type: integer
                    type: object
              type: object
        "400":
          description: Bad Request <br>Detail value type can change depends on main
            error
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  allOf:
                  - type: object
                  - properties:
                      code:
                        type: integer
                      description:
                        type: string
                      detail:
                        type: object
                    type: object
              type: object
        "404":
          description: Not Found <br>Detail value type can change depends on main
            error
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  allOf:
                  - type: object
                  - properties:
                      code:
                        type: integer
                      description:
                        type: string
                      detail:
                        type: object
                    type: object
              type: object
        "409":
          description: Conflict <br>Detail value type can change depends on main error
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  allOf:
                  - type: object
                  - properties:
                      code:
                        type: integer
                      description:
                        type: string
                      detail:
                        type: object
                    type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  allOf:
                  - type: object
                  - properties:
                      code:
                        type: integer
                      description:
                        type: string
                    type: object
              type: object
      summary: Delete
      tags:
      - Delete
swagger: "2.0"
